insert into application (dtype, id, name, sponsor) values ('LiveSession', 1, 'Alberik Jebb', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 2, 'Abba Gawthrope', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 3, 'Sabra Cupitt', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 4, 'Julee Sherwill', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 5, 'Adriane Fogt', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 6, 'Lizzy Wakerley', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 7, 'Olin Peake', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 8, 'Nannie Ramlot', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 9, 'Moss Gatward', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 10, 'Derrick Falkinder', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 11, 'Jere Doge', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 12, 'Ilka Footer', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 13, 'Dalton Bread', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 14, 'Quintin Giffen', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 15, 'Elfrida Dumberrill', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 16, 'Cass Gobbet', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 17, 'Lexis Murley', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 18, 'Erie Kenningley', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 19, 'Astra Grimsdale', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('LiveSession', 20, 'Shir Quinnelly', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 21, 'Teressa Philcox', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 22, 'Filip Ruecastle', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 23, 'Eirena Rawes', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 24, 'Levi Muscott', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 25, 'Beck Piscopiello', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 26, 'Gabriela Wathey', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 27, 'Zelma Acreman', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 28, 'Ignacius Pentlow', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 29, 'Toiboid Youster', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 30, 'Nevile Benini', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 31, 'Bertina Cavan', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 32, 'Tabitha Dutteridge', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 33, 'Emmit Ackhurst', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 34, 'Ashlee Jacqueminot', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 35, 'Starlin McCurdy', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 36, 'Gaspar Braybrooke', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 37, 'Mathian Darthe', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 38, 'Brunhilda Brandon', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 39, 'Simon Melvin', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Diary', 40, 'Koralle Brower', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 41, 'Bank Huet', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 42, 'Damaris Uvedale', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 43, 'Bord Villaret', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 44, 'Avigdor Domenichelli', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 45, 'Cooper Crowden', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 46, 'Wang Yeulet', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 47, 'Orv Renackowna', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 48, 'Ingrid Horbart', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 49, 'Korrie Nolot', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 50, 'Lonnie Icom', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 51, 'Barb Burthom', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 52, 'Erek Berthomier', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 53, 'Inesita Fernier', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 54, 'Roshelle Lambricht', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 55, 'Delores Blitzer', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 56, 'Jennilee Wallis', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 57, 'Camella Leach', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 58, 'Charlie Deluze', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 59, 'Charline Peetermann', 'Sanitas AG');
insert into application (dtype, id, name, sponsor) values ('Workout', 60, 'Foster Greener', 'Sanitas AG');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 1, 50, 'M', 'Madison Fiddiman', 6, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 2, 28, 'F', 'Iolanthe Minton', 29, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 3, 27, 'M', 'Tremayne Esposi', 39, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 4, 30, 'F', 'Paige Loveman', 23, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 5, 57, 'M', 'Gray Meyrick', 37, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 6, 59, 'M', 'Mendel Gasperi', 19, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 7, 36, 'M', 'Bryon Vanelli', 21, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 8, 19, 'M', 'Chester Manuele', 21, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 9, 60, 'F', 'Ezmeralda Riden', 35, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 10, 52, 'F', 'Katti Borges', 21, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 11, 28, 'M', 'Baudoin Schreiner', 33, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 12, 19, 'F', 'Pauli Spottiswoode', 17, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 13, 47, 'M', 'Matthias Matskiv', 9, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 14, 30, 'F', 'Rowena Adamec', 21, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 15, 55, 'M', 'Andreas Kervin', 4, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 16, 29, 'F', 'Glen Ayres', 14, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 17, 19, 'M', 'Woodman Idiens', 30, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 18, 36, 'M', 'Johan Ogdahl', 13, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 19, 21, 'M', 'Jonathon Broomhead', 38, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 20, 21, 'F', 'Anne Glazzard', 29, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 21, 55, 'M', 'Vince Matusevich', 39, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 22, 50, 'M', 'Bogey Prettejohns', 19, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 23, 23, 'M', 'Franny Aprahamian', 16, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 24, 34, 'M', 'Bogey Cranshaw', 29, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 25, 64, 'F', 'Diann Skews', 24, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 26, 31, 'M', 'Saxon Odcroft', 13, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 27, 37, 'F', 'Mamie Alejandre', 37, 'Sport');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 28, 29, 'F', 'Vilma Harring', 27, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 29, 22, 'M', 'Ken MacKenzie', 20, 'Psychology');
insert into user (dtype, id, age, gender, name, experience, subject_area) values ('Coach', 30, 32, 'F', 'Loraine Beaston', 29, 'Sport');
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 31, 37, 'M', 'Omar Wiffield', 'mental', 'Sanitas', 37);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 32, 55, 'F', 'Sarine Petrelluzzi', 'physical', 'Sanitas', 7);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 33, 48, 'F', 'Madge Nelligan', 'mental', 'Sanitas', 17);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 34, 31, 'M', 'Woody Ashfull', 'mental', 'Sanitas', 42);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 35, 55, 'F', 'Norri Androletti', 'mental', 'Helsana', 23);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 36, 40, 'M', 'Dell Jamison', 'physical', 'Sanitas', 60);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 37, 56, 'M', 'Cletis Limbrick', 'mental', 'Helsana', 58);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 38, 34, 'M', 'Even Yare', 'mental', 'Sanitas', 25);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 39, 33, 'M', 'Quincy Reid', 'mental', 'Visana', 39);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 40, 32, 'F', 'Dulce Flode', 'mental', 'Visana', 45);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 41, 50, 'F', 'Sherill Veart', 'mental', 'Sanitas', 53);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 42, 26, 'F', 'Tarah Ordemann', 'mental', 'Helsana', 2);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 43, 23, 'M', 'Lou Hanigan', 'physical', 'Visana', 35);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 44, 31, 'M', 'Jecho Sanbroke', 'physical', 'SWICA', 50);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 45, 44, 'F', 'Lib Nortunen', 'physical', 'Visana', 25);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 46, 43, 'M', 'Maximilianus Pashan', 'physical', 'SWICA', 40);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 47, 21, 'M', 'Haley Verdie', 'physical', 'Sanitas', 8);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 48, 20, 'F', 'Merline Chettoe', 'mental', 'Sanitas', 30);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 49, 39, 'F', 'Elvera Pettett', 'physical', 'Helsana', 21);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 50, 55, 'M', 'Julian Gawkroge', 'mental', 'Helsana', 49);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 51, 60, 'M', 'Ripley Raisbeck', 'physical', 'SWICA', 45);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 52, 48, 'F', 'Wylma Buddington', 'physical', 'Visana', 32);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 53, 24, 'F', 'Billye Pagin', 'physical', 'Visana', 57);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 54, 21, 'F', 'Jorey Fantham', 'mental', 'Helsana', 19);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 55, 63, 'M', 'Orion Durran', 'mental', 'Helsana', 26);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 56, 57, 'F', 'Bobine Scarce', 'mental', 'SWICA', 40);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 57, 62, 'F', 'Jorie Middler', 'mental', 'Visana', 48);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 58, 53, 'F', 'Blondell Mariaud', 'physical', 'Visana', 59);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 59, 35, 'M', 'Brannon Callaghan', 'mental', 'Visana', 39);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 60, 36, 'F', 'Eleonore Greeno', 'mental', 'SWICA', 56);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 61, 23, 'M', 'Dugald Bagott', 'physical', 'SWICA', 12);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 62, 58, 'M', 'Lloyd O''Skehan', 'mental', 'Visana', 5);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 63, 48, 'F', 'Dixie Whatson', 'mental', 'Visana', 52);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 64, 51, 'M', 'Terencio Lilleman', 'mental', 'Visana', 38);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 65, 48, 'F', 'Shae Cranch', 'mental', 'SWICA', 26);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 66, 64, 'M', 'Chick Quinevan', 'physical', 'SWICA', 44);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 67, 53, 'F', 'Marcie Alelsandrowicz', 'mental', 'Helsana', 2);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 68, 44, 'F', 'Aaren Pfaff', 'physical', 'Helsana', 42);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 69, 42, 'F', 'Bianca Bartosik', 'physical', 'Helsana', 39);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 70, 46, 'F', 'Maryjo Oganian', 'physical', 'Sanitas', 54);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 71, 61, 'M', 'Grover Twigger', 'mental', 'Sanitas', 53);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 72, 63, 'F', 'Bunny Lukes', 'physical', 'Visana', 22);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 73, 53, 'F', 'Jillene Conibere', 'mental', 'Visana', 29);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 74, 39, 'M', 'Hartwell Quirke', 'mental', 'SWICA', 12);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 75, 35, 'M', 'Hinze Zylberdik', 'physical', 'Sanitas', 53);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 76, 27, 'F', 'Gabbie Korfmann', 'mental', 'Helsana', 26);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 77, 46, 'M', 'Constantino Chessun', 'mental', 'Helsana', 26);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 78, 63, 'F', 'Joy Erbain', 'physical', 'Visana', 23);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 79, 58, 'F', 'Tracee Simonite', 'mental', 'Sanitas', 33);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 80, 59, 'M', 'Boris Corwin', 'physical', 'SWICA', 53);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 81, 51, 'F', 'Fionna Grice', 'physical', 'Helsana', 16);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 82, 60, 'F', 'Tamqrah Boagey', 'physical', 'SWICA', 32);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 83, 24, 'M', 'Steward Chern', 'physical', 'Sanitas', 42);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 84, 49, 'M', 'Denver Game', 'mental', 'Sanitas', 39);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 85, 40, 'M', 'Lyon Rixon', 'mental', 'SWICA', 37);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 86, 57, 'F', 'Gerty Becerra', 'physical', 'Visana', 36);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 87, 20, 'F', 'Geraldine Manion', 'mental', 'Sanitas', 54);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 88, 37, 'M', 'Torrance Beavon', 'physical', 'Helsana', 45);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 89, 33, 'F', 'Bibbie Rozycki', 'physical', 'Helsana', 49);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 90, 59, 'M', 'Wit Wetherhead', 'mental', 'Visana', 53);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 91, 64, 'M', 'Alberik Raspel', 'mental', 'Visana', 36);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 92, 32, 'M', 'Darbee Ackenhead', 'physical', 'Visana', 57);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 93, 36, 'M', 'Halsy Wittering', 'physical', 'Visana', 10);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 94, 26, 'M', 'Sean Hulmes', 'mental', 'SWICA', 15);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 95, 35, 'M', 'Zackariah Gales', 'physical', 'Helsana', 39);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 96, 29, 'M', 'Dugald Rummin', 'physical', 'SWICA', 58);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 97, 47, 'F', 'Elianore Heath', 'mental', 'Visana', 8);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 98, 23, 'M', 'Alix Robbe', 'physical', 'SWICA', 34);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 99, 47, 'F', 'Sandye Blaxley', 'mental', 'Sanitas', 46);
insert into user (dtype, id, age, gender, name, goal, insurance, fk_application_id) values ('Customer', 100, 48, 'M', 'Hubie Hollington', 'physical', 'Visana', 5);
insert into entry (id, date, progress, note, fk_diary_id) values (1, '01/06/2020', 1, 'Nulla ut erat id mauris vulputate elementum.', 21);
insert into entry (id, date, progress, note, fk_diary_id) values (2, '29/08/2020', 3, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 21);
insert into entry (id, date, progress, note, fk_diary_id) values (3, '06/11/2020', 4, 'Morbi a ipsum.', 30);
insert into entry (id, date, progress, note, fk_diary_id) values (4, '20/06/2020', 10, 'Cras in purus eu magna vulputate luctus.', 22);
insert into entry (id, date, progress, note, fk_diary_id) values (5, '14/03/2021', 10, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 30);
insert into entry (id, date, progress, note, fk_diary_id) values (6, '15/11/2020', 9, 'In blandit ultrices enim.', 33);
insert into entry (id, date, progress, note, fk_diary_id) values (7, '08/12/2020', 10, 'Nunc purus.', 33);
insert into entry (id, date, progress, note, fk_diary_id) values (8, '16/10/2020', 6, 'Vivamus vestibulum sagittis sapien.', 32);
insert into entry (id, date, progress, note, fk_diary_id) values (9, '21/12/2020', 10, 'Phasellus in felis.', 40);
insert into entry (id, date, progress, note, fk_diary_id) values (10, '07/09/2020', 3, 'Aliquam quis turpis eget elit sodales scelerisque.', 38);
insert into entry (id, date, progress, note, fk_diary_id) values (11, '10/04/2021', 7, 'Curabitur gravida nisi at nibh.', 32);
insert into entry (id, date, progress, note, fk_diary_id) values (12, '14/02/2021', 10, 'Nam dui.', 33);
insert into entry (id, date, progress, note, fk_diary_id) values (13, '18/11/2020', 8, 'Proin at turpis a pede posuere nonummy.', 29);
insert into entry (id, date, progress, note, fk_diary_id) values (14, '06/01/2021', 4, 'Nam dui.', 34);
insert into entry (id, date, progress, note, fk_diary_id) values (15, '09/05/2021', 7, 'Aliquam erat volutpat.', 37);
insert into entry (id, date, progress, note, fk_diary_id) values (16, '14/08/2020', 7, 'Curabitur convallis.', 35);
insert into entry (id, date, progress, note, fk_diary_id) values (17, '15/08/2020', 2, 'Duis ac nibh.', 21);
insert into entry (id, date, progress, note, fk_diary_id) values (18, '06/01/2021', 8, 'Cras non velit nec nisi vulputate nonummy.', 29);
insert into entry (id, date, progress, note, fk_diary_id) values (19, '07/02/2021', 1, 'Morbi porttitor lorem id ligula.', 26);
insert into entry (id, date, progress, note, fk_diary_id) values (20, '22/03/2021', 7, 'Donec semper sapien a libero.', 39);
insert into entry (id, date, progress, note, fk_diary_id) values (21, '09/12/2020', 1, 'Vivamus vel nulla eget eros elementum pellentesque.', 36);
insert into entry (id, date, progress, note, fk_diary_id) values (22, '18/03/2021', 5, 'Pellentesque at nulla.', 37);
insert into entry (id, date, progress, note, fk_diary_id) values (23, '29/11/2020', 8, 'Nulla tempus.', 24);
insert into entry (id, date, progress, note, fk_diary_id) values (24, '01/11/2020', 9, 'In hac habitasse platea dictumst.', 23);
insert into entry (id, date, progress, note, fk_diary_id) values (25, '10/05/2021', 3, 'Cras pellentesque volutpat dui.', 26);
insert into entry (id, date, progress, note, fk_diary_id) values (26, '06/12/2020', 10, 'In eleifend quam a odio.', 24);
insert into entry (id, date, progress, note, fk_diary_id) values (27, '03/03/2021', 8, 'Fusce consequat.', 21);
insert into entry (id, date, progress, note, fk_diary_id) values (28, '14/03/2021', 8, 'Sed vel enim sit amet nunc viverra dapibus.', 22);
insert into entry (id, date, progress, note, fk_diary_id) values (29, '18/09/2020', 1, 'Ut tellus.', 33);
insert into entry (id, date, progress, note, fk_diary_id) values (30, '26/04/2021', 5, 'Vivamus in felis eu sapien cursus vestibulum.', 35);
insert into entry (id, date, progress, note, fk_diary_id) values (31, '05/09/2020', 3, 'Suspendisse accumsan tortor quis turpis.', 31);
insert into entry (id, date, progress, note, fk_diary_id) values (32, '24/05/2021', 10, 'Integer ac leo.', 32);
insert into entry (id, date, progress, note, fk_diary_id) values (33, '09/07/2020', 2, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 21);
insert into entry (id, date, progress, note, fk_diary_id) values (34, '24/08/2020', 10, 'Donec posuere metus vitae ipsum.', 40);
insert into entry (id, date, progress, note, fk_diary_id) values (35, '26/01/2021', 10, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 38);
insert into entry (id, date, progress, note, fk_diary_id) values (36, '13/12/2020', 8, 'Morbi quis tortor id nulla ultrices aliquet.', 23);
insert into entry (id, date, progress, note, fk_diary_id) values (37, '22/05/2021', 7, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 37);
insert into entry (id, date, progress, note, fk_diary_id) values (38, '20/03/2021', 2, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 34);
insert into entry (id, date, progress, note, fk_diary_id) values (39, '25/07/2020', 7, 'Fusce posuere felis sed lacus.', 34);
insert into entry (id, date, progress, note, fk_diary_id) values (40, '05/11/2020', 2, 'Nulla nisl.', 31);
insert into entry (id, date, progress, note, fk_diary_id) values (41, '11/04/2021', 5, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 21);
insert into entry (id, date, progress, note, fk_diary_id) values (42, '16/06/2020', 4, 'Aliquam sit amet diam in magna bibendum imperdiet.', 32);
insert into entry (id, date, progress, note, fk_diary_id) values (43, '06/03/2021', 9, 'Cras in purus eu magna vulputate luctus.', 31);
insert into entry (id, date, progress, note, fk_diary_id) values (44, '04/12/2020', 9, 'Donec posuere metus vitae ipsum.', 31);
insert into entry (id, date, progress, note, fk_diary_id) values (45, '03/08/2020', 9, 'Fusce consequat.', 36);
insert into entry (id, date, progress, note, fk_diary_id) values (46, '11/01/2021', 7, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 24);
insert into entry (id, date, progress, note, fk_diary_id) values (47, '30/07/2020', 10, 'Proin at turpis a pede posuere nonummy.', 22);
insert into entry (id, date, progress, note, fk_diary_id) values (48, '22/10/2020', 5, 'Vestibulum sed magna at nunc commodo placerat.', 37);
insert into entry (id, date, progress, note, fk_diary_id) values (49, '21/12/2020', 2, 'Nunc nisl.', 22);
insert into entry (id, date, progress, note, fk_diary_id) values (50, '27/05/2021', 5, 'Aliquam non mauris.', 25);
insert into session (id, duration, topic, fk_live_session_id) values (1, '3:47', 'Sabaigrass', 16);
insert into session (id, duration, topic, fk_live_session_id) values (2, '15:13', 'Brandegee''s Tansyaster', 9);
insert into session (id, duration, topic, fk_live_session_id) values (3, '8:13', 'Kopa', 15);
insert into session (id, duration, topic, fk_live_session_id) values (4, '14:14', 'Timmia Moss', 20);
insert into session (id, duration, topic, fk_live_session_id) values (5, '21:58', 'Kansas Fissidens Moss', 6);
insert into session (id, duration, topic, fk_live_session_id) values (6, '11:49', 'Redwood Lily', 17);
insert into session (id, duration, topic, fk_live_session_id) values (7, '19:19', 'Enterographa Lichen', 5);
insert into session (id, duration, topic, fk_live_session_id) values (8, '2:34', 'Bog White Violet', 17);
insert into session (id, duration, topic, fk_live_session_id) values (9, '20:02', 'Tall Ironweed', 4);
insert into session (id, duration, topic, fk_live_session_id) values (10, '4:18', 'Mapleleaf Grape', 9);
insert into session (id, duration, topic, fk_live_session_id) values (11, '2:18', 'Yucca Plum Pine', 1);
insert into session (id, duration, topic, fk_live_session_id) values (12, '9:58', 'Dixie Iris', 17);
insert into session (id, duration, topic, fk_live_session_id) values (13, '13:01', 'Golden Suncup', 2);
insert into session (id, duration, topic, fk_live_session_id) values (14, '2:25', 'Madera Linanthus', 1);
insert into session (id, duration, topic, fk_live_session_id) values (15, '20:48', 'Rollins'' Twinpod', 10);
insert into session (id, duration, topic, fk_live_session_id) values (16, '7:32', 'Coastal Dunes Milkvetch', 14);
insert into session (id, duration, topic, fk_live_session_id) values (17, '4:30', 'Colicwood', 14);
insert into session (id, duration, topic, fk_live_session_id) values (18, '11:03', 'Nalta Jute', 9);
insert into session (id, duration, topic, fk_live_session_id) values (19, '18:53', 'Yellow Birch', 2);
insert into session (id, duration, topic, fk_live_session_id) values (20, '14:23', 'Arctomia Lichen', 16);
insert into session (id, duration, topic, fk_live_session_id) values (21, '3:49', 'Maximowicz''s Myuroclada Moss', 12);
insert into session (id, duration, topic, fk_live_session_id) values (22, '14:00', 'Desert Indianwheat', 10);
insert into session (id, duration, topic, fk_live_session_id) values (23, '6:32', 'Golden Mock Orange', 14);
insert into session (id, duration, topic, fk_live_session_id) values (24, '3:26', 'Toumey''s Century Plant', 13);
insert into session (id, duration, topic, fk_live_session_id) values (25, '10:21', 'Guavaberry', 19);
insert into session (id, duration, topic, fk_live_session_id) values (26, '19:52', 'Joewood', 15);
insert into session (id, duration, topic, fk_live_session_id) values (27, '12:06', 'Lichenosticta Lichen', 11);
insert into session (id, duration, topic, fk_live_session_id) values (28, '7:35', 'Fringetree', 3);
insert into session (id, duration, topic, fk_live_session_id) values (29, '13:03', 'Bryum Moss', 15);
insert into session (id, duration, topic, fk_live_session_id) values (30, '15:45', 'Columbiadoria', 19);
insert into session (id, duration, topic, fk_live_session_id) values (31, '15:18', 'Fringed Brome', 4);
insert into session (id, duration, topic, fk_live_session_id) values (32, '4:41', 'Desert-chicory', 11);
insert into session (id, duration, topic, fk_live_session_id) values (33, '12:59', 'Kauai Spurge', 11);
insert into session (id, duration, topic, fk_live_session_id) values (34, '19:39', 'Pale Indian Paintbrush', 8);
insert into session (id, duration, topic, fk_live_session_id) values (35, '15:53', 'California Amaranth', 4);
insert into session (id, duration, topic, fk_live_session_id) values (36, '13:55', 'Parry''s Wormwood', 9);
insert into session (id, duration, topic, fk_live_session_id) values (37, '10:02', 'Yankeeweed', 12);
insert into session (id, duration, topic, fk_live_session_id) values (38, '21:52', 'Trans-pecos Morning-glory', 16);
insert into session (id, duration, topic, fk_live_session_id) values (39, '2:15', 'Fairywand', 1);
insert into session (id, duration, topic, fk_live_session_id) values (40, '20:08', 'Texas Bittercress', 15);
insert into session (id, duration, topic, fk_live_session_id) values (41, '22:23', 'Featherweed', 4);
insert into session (id, duration, topic, fk_live_session_id) values (42, '0:10', 'Ring Lichen', 4);
insert into session (id, duration, topic, fk_live_session_id) values (43, '9:06', 'Chestnutleaf Trumpetbush', 4);
insert into session (id, duration, topic, fk_live_session_id) values (44, '20:28', 'Coccuswood', 5);
insert into session (id, duration, topic, fk_live_session_id) values (45, '22:41', 'Snow Squarestem', 17);
insert into session (id, duration, topic, fk_live_session_id) values (46, '18:59', 'Canadian White Violet', 10);
insert into session (id, duration, topic, fk_live_session_id) values (47, '8:58', 'Western Trailing Ticktrefoil', 10);
insert into session (id, duration, topic, fk_live_session_id) values (48, '4:57', 'Florida Adder''s-mouth Orchid', 12);
insert into session (id, duration, topic, fk_live_session_id) values (49, '5:40', 'Thompson''s Waterleaf', 3);
insert into session (id, duration, topic, fk_live_session_id) values (50, '4:14', 'Green Dragon', 4);
insert into training (id, duration, level, fk_workout_id) values (1, '15:02', 5, 59);
insert into training (id, duration, level, fk_workout_id) values (2, '6:20', 2, 59);
insert into training (id, duration, level, fk_workout_id) values (3, '11:29', 3, 55);
insert into training (id, duration, level, fk_workout_id) values (4, '4:30', 3, 47);
insert into training (id, duration, level, fk_workout_id) values (5, '5:56', 2, 57);
insert into training (id, duration, level, fk_workout_id) values (6, '12:47', 1, 56);
insert into training (id, duration, level, fk_workout_id) values (7, '13:03', 1, 42);
insert into training (id, duration, level, fk_workout_id) values (8, '15:26', 4, 46);
insert into training (id, duration, level, fk_workout_id) values (9, '7:10', 5, 46);
insert into training (id, duration, level, fk_workout_id) values (10, '11:59', 6, 58);
insert into training (id, duration, level, fk_workout_id) values (11, '12:29', 6, 48);
insert into training (id, duration, level, fk_workout_id) values (12, '15:53', 5, 44);
insert into training (id, duration, level, fk_workout_id) values (13, '14:14', 3, 57);
insert into training (id, duration, level, fk_workout_id) values (14, '15:55', 1, 53);
insert into training (id, duration, level, fk_workout_id) values (15, '10:55', 3, 54);
insert into training (id, duration, level, fk_workout_id) values (16, '16:34', 5, 57);
insert into training (id, duration, level, fk_workout_id) values (17, '13:33', 1, 41);
insert into training (id, duration, level, fk_workout_id) values (18, '8:39', 4, 53);
insert into training (id, duration, level, fk_workout_id) values (19, '16:52', 5, 49);
insert into training (id, duration, level, fk_workout_id) values (20, '11:14', 6, 59);
insert into training (id, duration, level, fk_workout_id) values (21, '7:00', 4, 58);
insert into training (id, duration, level, fk_workout_id) values (22, '15:59', 5, 52);
insert into training (id, duration, level, fk_workout_id) values (23, '1:17', 3, 42);
insert into training (id, duration, level, fk_workout_id) values (24, '15:06', 3, 51);
insert into training (id, duration, level, fk_workout_id) values (25, '13:26', 4, 59);
insert into training (id, duration, level, fk_workout_id) values (26, '15:16', 2, 44);
insert into training (id, duration, level, fk_workout_id) values (27, '2:14', 3, 41);
insert into training (id, duration, level, fk_workout_id) values (28, '2:46', 5, 50);
insert into training (id, duration, level, fk_workout_id) values (29, '5:49', 5, 44);
insert into training (id, duration, level, fk_workout_id) values (30, '8:27', 6, 42);
insert into training (id, duration, level, fk_workout_id) values (31, '7:59', 3, 52);
insert into training (id, duration, level, fk_workout_id) values (32, '1:56', 3, 41);
insert into training (id, duration, level, fk_workout_id) values (33, '10:19', 4, 51);
insert into training (id, duration, level, fk_workout_id) values (34, '4:56', 3, 57);
insert into training (id, duration, level, fk_workout_id) values (35, '16:39', 6, 46);
insert into training (id, duration, level, fk_workout_id) values (36, '13:26', 4, 52);
insert into training (id, duration, level, fk_workout_id) values (37, '16:06', 1, 45);
insert into training (id, duration, level, fk_workout_id) values (38, '2:53', 5, 42);
insert into training (id, duration, level, fk_workout_id) values (39, '9:40', 3, 54);
insert into training (id, duration, level, fk_workout_id) values (40, '8:25', 3, 49);
insert into training (id, duration, level, fk_workout_id) values (41, '13:27', 1, 50);
insert into training (id, duration, level, fk_workout_id) values (42, '14:22', 4, 48);
insert into training (id, duration, level, fk_workout_id) values (43, '5:30', 1, 53);
insert into training (id, duration, level, fk_workout_id) values (44, '14:49', 3, 45);
insert into training (id, duration, level, fk_workout_id) values (45, '3:26', 5, 50);
insert into training (id, duration, level, fk_workout_id) values (46, '8:05', 1, 48);
insert into training (id, duration, level, fk_workout_id) values (47, '3:32', 1, 41);
insert into training (id, duration, level, fk_workout_id) values (48, '5:06', 3, 47);
insert into training (id, duration, level, fk_workout_id) values (49, '14:09', 3, 52);
insert into training (id, duration, level, fk_workout_id) values (50, '5:17', 3, 46);
