insert into session (id, duration, topic, live_session_id) values (1, '3:47', 'Sabaigrass', 16);
insert into session (id, duration, topic, live_session_id) values (2, '15:13', 'Brandegee''s Tansyaster', 9);
insert into session (id, duration, topic, live_session_id) values (3, '8:13', 'Kopa', 15);
insert into session (id, duration, topic, live_session_id) values (4, '14:14', 'Timmia Moss', 20);
insert into session (id, duration, topic, live_session_id) values (5, '21:58', 'Kansas Fissidens Moss', 6);
insert into session (id, duration, topic, live_session_id) values (6, '11:49', 'Redwood Lily', 17);
insert into session (id, duration, topic, live_session_id) values (7, '19:19', 'Enterographa Lichen', 5);
insert into session (id, duration, topic, live_session_id) values (8, '2:34', 'Bog White Violet', 17);
insert into session (id, duration, topic, live_session_id) values (9, '20:02', 'Tall Ironweed', 4);
insert into session (id, duration, topic, live_session_id) values (10, '4:18', 'Mapleleaf Grape', 9);
insert into session (id, duration, topic, live_session_id) values (11, '2:18', 'Yucca Plum Pine', 1);
insert into session (id, duration, topic, live_session_id) values (12, '9:58', 'Dixie Iris', 17);
insert into session (id, duration, topic, live_session_id) values (13, '13:01', 'Golden Suncup', 2);
insert into session (id, duration, topic, live_session_id) values (14, '2:25', 'Madera Linanthus', 1);
insert into session (id, duration, topic, live_session_id) values (15, '20:48', 'Rollins'' Twinpod', 10);
insert into session (id, duration, topic, live_session_id) values (16, '7:32', 'Coastal Dunes Milkvetch', 14);
insert into session (id, duration, topic, live_session_id) values (17, '4:30', 'Colicwood', 14);
insert into session (id, duration, topic, live_session_id) values (18, '11:03', 'Nalta Jute', 9);
insert into session (id, duration, topic, live_session_id) values (19, '18:53', 'Yellow Birch', 2);
insert into session (id, duration, topic, live_session_id) values (20, '14:23', 'Arctomia Lichen', 16);
insert into session (id, duration, topic, live_session_id) values (21, '3:49', 'Maximowicz''s Myuroclada Moss', 12);
insert into session (id, duration, topic, live_session_id) values (22, '14:00', 'Desert Indianwheat', 10);
insert into session (id, duration, topic, live_session_id) values (23, '6:32', 'Golden Mock Orange', 14);
insert into session (id, duration, topic, live_session_id) values (24, '3:26', 'Toumey''s Century Plant', 13);
insert into session (id, duration, topic, live_session_id) values (25, '10:21', 'Guavaberry', 19);
insert into session (id, duration, topic, live_session_id) values (26, '19:52', 'Joewood', 15);
insert into session (id, duration, topic, live_session_id) values (27, '12:06', 'Lichenosticta Lichen', 11);
insert into session (id, duration, topic, live_session_id) values (28, '7:35', 'Fringetree', 3);
insert into session (id, duration, topic, live_session_id) values (29, '13:03', 'Bryum Moss', 15);
insert into session (id, duration, topic, live_session_id) values (30, '15:45', 'Columbiadoria', 19);
insert into session (id, duration, topic, live_session_id) values (31, '15:18', 'Fringed Brome', 4);
insert into session (id, duration, topic, live_session_id) values (32, '4:41', 'Desert-chicory', 11);
insert into session (id, duration, topic, live_session_id) values (33, '12:59', 'Kauai Spurge', 11);
insert into session (id, duration, topic, live_session_id) values (34, '19:39', 'Pale Indian Paintbrush', 8);
insert into session (id, duration, topic, live_session_id) values (35, '15:53', 'California Amaranth', 4);
insert into session (id, duration, topic, live_session_id) values (36, '13:55', 'Parry''s Wormwood', 9);
insert into session (id, duration, topic, live_session_id) values (37, '10:02', 'Yankeeweed', 12);
insert into session (id, duration, topic, live_session_id) values (38, '21:52', 'Trans-pecos Morning-glory', 16);
insert into session (id, duration, topic, live_session_id) values (39, '2:15', 'Fairywand', 1);
insert into session (id, duration, topic, live_session_id) values (40, '20:08', 'Texas Bittercress', 15);
insert into session (id, duration, topic, live_session_id) values (41, '22:23', 'Featherweed', 4);
insert into session (id, duration, topic, live_session_id) values (42, '0:10', 'Ring Lichen', 4);
insert into session (id, duration, topic, live_session_id) values (43, '9:06', 'Chestnutleaf Trumpetbush', 4);
insert into session (id, duration, topic, live_session_id) values (44, '20:28', 'Coccuswood', 5);
insert into session (id, duration, topic, live_session_id) values (45, '22:41', 'Snow Squarestem', 17);
insert into session (id, duration, topic, live_session_id) values (46, '18:59', 'Canadian White Violet', 10);
insert into session (id, duration, topic, live_session_id) values (47, '8:58', 'Western Trailing Ticktrefoil', 10);
insert into session (id, duration, topic, live_session_id) values (48, '4:57', 'Florida Adder''s-mouth Orchid', 12);
insert into session (id, duration, topic, live_session_id) values (49, '5:40', 'Thompson''s Waterleaf', 3);
insert into session (id, duration, topic, live_session_id) values (50, '4:14', 'Green Dragon', 4);
