insert into session (id, duration, topic, fk_live_session_id) values (1, '16:58', 'Club Lichen', 17);
insert into session (id, duration, topic, fk_live_session_id) values (2, '12:00', 'Peruvian Spikemoss', 14);
insert into session (id, duration, topic, fk_live_session_id) values (3, '2:13', 'Mate', 3);
insert into session (id, duration, topic, fk_live_session_id) values (4, '6:57', 'Script Lichen', 20);
insert into session (id, duration, topic, fk_live_session_id) values (5, '1:49', 'Layne''s Monkeyflower', 3);
insert into session (id, duration, topic, fk_live_session_id) values (6, '3:42', 'Snowberry', 1);
insert into session (id, duration, topic, fk_live_session_id) values (7, '0:21', 'Turner''s Hawthorn', 8);
insert into session (id, duration, topic, fk_live_session_id) values (8, '2:31', 'Fernaldia', 14);
insert into session (id, duration, topic, fk_live_session_id) values (9, '14:33', 'Wedgeleaf Draba', 11);
insert into session (id, duration, topic, fk_live_session_id) values (10, '18:36', 'Orthotrichum Moss', 12);
insert into session (id, duration, topic, fk_live_session_id) values (11, '8:19', 'Scarlet Spiral-ginger', 13);
insert into session (id, duration, topic, fk_live_session_id) values (12, '1:30', 'Rinodina Lichen', 19);
insert into session (id, duration, topic, fk_live_session_id) values (13, '11:42', 'Cockerell''s Stonecrop', 20);
insert into session (id, duration, topic, fk_live_session_id) values (14, '19:21', 'Jepson''s Bedstraw', 1);
insert into session (id, duration, topic, fk_live_session_id) values (15, '2:35', 'Godfrey''s False Dragonhead', 6);
insert into session (id, duration, topic, fk_live_session_id) values (16, '21:13', 'Lapland Rosebay', 14);
insert into session (id, duration, topic, fk_live_session_id) values (17, '11:59', 'Molokai Colicwood', 4);
insert into session (id, duration, topic, fk_live_session_id) values (18, '12:03', 'Texas False Garlic', 6);
insert into session (id, duration, topic, fk_live_session_id) values (19, '11:11', 'Barneby''s Clover', 9);
insert into session (id, duration, topic, fk_live_session_id) values (20, '3:59', 'Eggyolk Lichen', 10);
insert into session (id, duration, topic, fk_live_session_id) values (21, '7:21', 'Globe Candytuft', 11);
insert into session (id, duration, topic, fk_live_session_id) values (22, '16:06', 'Coastal Plain Angelica', 20);
insert into session (id, duration, topic, fk_live_session_id) values (23, '8:21', 'Creeping Baby''s-breath', 15);
insert into session (id, duration, topic, fk_live_session_id) values (24, '22:39', 'Trinity Sphagnum', 12);
insert into session (id, duration, topic, fk_live_session_id) values (25, '8:58', 'Lavender Woollystar', 5);
insert into session (id, duration, topic, fk_live_session_id) values (26, '7:30', 'Mamoncillo', 4);
insert into session (id, duration, topic, fk_live_session_id) values (27, '11:01', 'White Panicle Aster', 3);
insert into session (id, duration, topic, fk_live_session_id) values (28, '22:05', 'Goldback Fern', 16);
insert into session (id, duration, topic, fk_live_session_id) values (29, '20:41', 'Zonal Geranium', 5);
insert into session (id, duration, topic, fk_live_session_id) values (30, '11:29', 'Red Hempnettle', 8);
insert into session (id, duration, topic, fk_live_session_id) values (31, '22:45', 'Lanceleaf Tickseed', 9);
insert into session (id, duration, topic, fk_live_session_id) values (32, '22:19', 'Goose Tongue', 19);
insert into session (id, duration, topic, fk_live_session_id) values (33, '19:44', 'Sweet White Violet', 20);
insert into session (id, duration, topic, fk_live_session_id) values (34, '16:48', 'Blacktack Phacelia', 6);
insert into session (id, duration, topic, fk_live_session_id) values (35, '5:29', 'Yellowtuft', 14);
insert into session (id, duration, topic, fk_live_session_id) values (36, '10:52', 'Parry''s Sedge', 15);
insert into session (id, duration, topic, fk_live_session_id) values (37, '21:19', 'Common Alplily', 19);
insert into session (id, duration, topic, fk_live_session_id) values (38, '19:18', 'Locust', 11);
insert into session (id, duration, topic, fk_live_session_id) values (39, '1:29', 'Trujillo Coca', 9);
insert into session (id, duration, topic, fk_live_session_id) values (40, '15:41', 'Tolmie Star-tulip', 1);
insert into session (id, duration, topic, fk_live_session_id) values (41, '5:49', 'Peony', 5);
insert into session (id, duration, topic, fk_live_session_id) values (42, '14:50', 'Divided Rockcress', 9);
insert into session (id, duration, topic, fk_live_session_id) values (43, '23:52', 'Scarlet Beardtongue', 17);
insert into session (id, duration, topic, fk_live_session_id) values (44, '9:03', 'Maricao Rodwood', 8);
insert into session (id, duration, topic, fk_live_session_id) values (45, '11:16', 'Shaggy Blazing Star', 9);
insert into session (id, duration, topic, fk_live_session_id) values (46, '2:09', 'Schlegelia', 11);
insert into session (id, duration, topic, fk_live_session_id) values (47, '0:42', 'Vervain', 8);
insert into session (id, duration, topic, fk_live_session_id) values (48, '21:03', 'Hippocratea', 17);
insert into session (id, duration, topic, fk_live_session_id) values (49, '10:46', 'Blue Ridge Shield Lichen', 9);
insert into session (id, duration, topic, fk_live_session_id) values (50, '7:19', 'Chamaedorea', 16);
